###########################################################################
#
# Configuration file for RINS command line run
#
# Please give the Whole Path of a file, and do not include space in file names
#
# example as follows
#
# Please fill all the required parameters
#
###########################################################################
#
#
#				THIS IS FOR THE RUBY VERSION ONLY
#
#
###########################################################################


# file format can be either "fasta" or "fastq"
:file_format: fasta

#	files is a hash
#		the keys should either be left and right or just single
:files:
  :left:  /Users/jakewendt/rins_test/rins/test_sample/testset_forkun_1.fa
  :right: /Users/jakewendt/rins_test/rins/test_sample/testset_forkun_2.fa
#:files:
#  :left:  /Users/jakewendt/rins_test/rins/test_sample/testset_forkun_1_chopped_25.fa
#  :right: /Users/jakewendt/rins_test/rins/test_sample/testset_forkun_2_chopped_25.fa

# email notification (not enabled at the moment, nevertheless)
:mailto:  jakewendt@berkeley.edu

#	if the raw files are fasta, link them instead of copying them in
:link_sample_fa_files: true

#
#	If pre_chopped, the chopped filename must be the same as the raw
#	file name with "_chopped_#{chop_read_length}" at end before extension.
#
#	testset_forkun_1.fa -> testset_forkun_1_chopped_25.fa
#
:pre_chopped: true

# reference files
#	Only the blat_reference index uses the .fa suffix 
#:blat_reference:         /Users/jakewendt/rins/indexes/virus.fa
:blat_reference:         /Volumes/cube/working/indexes/all_bacterial_and_virus.fa
:bowtie_index_human:     /Users/jakewendt/rins/indexes/hg18
:blastn_index_human:     /Users/jakewendt/rins/indexes/hg18
:blastn_index_non_human: /Users/jakewendt/rins/indexes/virus

